apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: assisted-image-service-gkcl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/assisted-image-service/assisted-image-service-gkcl@sha256:c4c30963020b85d9c1ebe56b71041d30dac488c55c6533570da60a92c7d25c1e
        name: my-go
        resources: {}
status: {}
