apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: assisted-image-service-gkcl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: assisted-image-service-gkcl
    app.kubernetes.io/part-of: assisted-image-service
  name: assisted-image-service-gkcl
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: assisted-image-service-gkcl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: assisted-image-service-gkcl
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/assisted-image-service/assisted-image-service-gkcl@sha256:c4c30963020b85d9c1ebe56b71041d30dac488c55c6533570da60a92c7d25c1e
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
