apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: assisted-image-service-gkcl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: assisted-image-service-gkcl
    app.kubernetes.io/part-of: assisted-image-service
  name: assisted-image-service-gkcl
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: assisted-image-service-gkcl
status:
  loadBalancer: {}
